### PR TITLE
Set correct value for hex 0x07 as result

### LINKED ISSUE #11: Wrong winner detected
Hello,

I am having an issue with the winner detection. Lady Risa replay tool detects the correct winner, but this lib detects the wrong winner. This is the example replay: 
[replay](https://creepcamp.de/media/replays/RBTV%20Liga%20Season%207/Liga%201/Paxa.United_vs_TapioN_Last_Refuge.w3g)
Winner should be player Tapion, but at least in my tests the lib detects the wrong winner.

Is this something that could be fixed anytime soon?

### PR DESCRIPTION
**Pull request by SantoDE**
Fixes #11

### CODE REVIEW

**Comment by scopatz** [comment]
Nice catch! Can you please add a news entry: https://regro.github.io/rever-docs/news.html

**Comment by SantoDE** [comment]
@scopatz 

Done. Hope that's fine?

**Comment by scopatz** [comment]
Yep, looks great thanks! Do you want me to do a release?

**Comment by SantoDE** [comment]
Yeah, that'd be awesome. Guess, it would help @kungfoolfighting

**Comment by scopatz** [comment]
Done! v1.0.4 should be out now

**Pull request merged**
