### PR TITLE
Add interface call to see if a race is picked by random

### PR DESCRIPTION
**Pull request by SantoDE**
Hey @scopatz,

last one for today ;-) We'd need an option to see if a race has been selected by random.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks! Can you please add a news entry: https://regro.github.io/rever-docs/news.html

**Comment by SantoDE** [comment]
Done @scopatz :)

**Comment by scopatz** [comment]
great thanks! let me know if/when you want  a release

**Comment by SantoDE** [comment]
Yes. We could need one @scopatz :p

**Comment by scopatz** [comment]
Done! v1.0.5 should be out now!

**Pull request merged**
